In [2]:
import pandas as pd

## rows with all the null values in loan_ledger.csv da

In [5]:
loan_ledger = pd.read_csv(r"C:\Users\Cleo\pydata\loan_ledger.csv",delimiter=",",encoding="utf-8")
loan_ledger

,loan_id,disbursement_date,amount,term_months,monthly_repayment,days_late
0,L1001,2025-06-16,pending,3.0,14760.0,45
1,L1002,2025-01-10,8000,12.0,720.0,-
2,L1003,2025-08-31,18500,3.0,6660.0,0
3,L1004,2025-09-07,NaN,6.0,6300.0,0
4,L1005,27/05/2025,15000,12.0,1350.0,0
...,...,...,...,...,...,...
58,L1059,09-May-2025,22000,6.0,3960.0,0
59,L1060,05-Jan-2025,30000,3.0,10800.0,0
60,NaN,NaN,NaN,NaN,NaN,NaN
61,TOTAL,NaN,=SUM(above),NaN,NaN,NaN
62,L1061,2025-08-02,-5000,6.0,900.0,0

## please consider this as my assignment, you can as well chech the other commented ideas to see what i was doing/ filtered successfully

In [35]:


# mask the cells containing true and false

# loan_ledger_mask = loan_ledger[["loan_id","disbursement_date","amount","term_months","monthly_repayment","days_late"]].isna()
# clean_loan_ledger_mask = loan_ledger_mask[~loan_ledger_mask]
# clean_loan_ledger_mask.reindex(index=range(63))

# cheking null values

# loan_ledger_mask = loan_ledger[loan_ledger.isna().any(axis=1)]
# clean_loan_ledger = loan_ledger_mask[~loan_ledger.isna().any(axis=1)]
# clean_loan_ledger.reindex(index=range(63))

clean_loan_ledger = loan_ledger.dropna().reset_index(drop=True)
clean_loan_ledger

,loan_id,disbursement_date,amount,term_months,monthly_repayment,days_late
0,L1001,2025-06-16,pending,3.0,14760.0,45
1,L1002,2025-01-10,8000,12.0,720.0,-
2,L1003,2025-08-31,18500,3.0,6660.0,0
3,L1005,27/05/2025,15000,12.0,1350.0,0
4,L1006,2025-04-06,35000,12.0,3150.0,-
5,L1007,20/04/2025,22000,6.0,3960.0,0
6,L1008,21-Jan-2025,22000,3.0,7920.0,5
7,L1009,31-Jan-2025,27000,6.0,4860.0,0
8,L1010,04-Sep-2025,pending,6.0,4860.0,0
9,L1011,02/06/2025,41000,6.0,7380.0,30
10,L1012,16-Jan-2025,30000,6.0,5400.0,0
11,L1013,16-Aug-2025,27000,6.0,4860.0,45
12,L1014,2025-01-16,35000,3.0,12600.0,0
13,L1015,12/02/2025,18500,6.0,3330.0,0
14,L1016,30/06/2025,18500,12.0,1665.0,15
15,L1017,2025-02-15,22000,3.0,7920.0,0
16,L1018,2025-03-14,KES 35000,3.0,12600.0,15
17,L1019,01-Sep-2025,41000,3.0,14760.0,0
18,L1020,13/04/2025,"9,500",6.0,1710.0,45
19,L1021,2025-02-11,12500,3.0,4500.0,-
20,L1022,31/08/2025,15000,12.0,1350.0,-
21,L1023,02/09/2025,18500,3.0,6660.0,15
22,L1024,04/05/2025,pending,6.0,4860.0,0
23,L1025,2025-05-13,30000,6.0,5400.0,0
24,L1026,18-Mar-2025,9500,3.0,3420.0,0
25,L1027,2025-07-17,41000,3.0,14760.0,30
26,L1028,2025-07-26,22000,12.0,1980.0,5
27,L1029,2025-07-07,9500,6.0,1710.0,30
28,L1030,25-Apr-2025,22000,12.0,1980.0,30
29,L1031,2025-05-01,22000,3.0,7920.0,5
30,L1032,21-Aug-2025,35000,3.0,12600.0,0
31,L1033,2025-05-03,12500,6.0,2250.0,5
32,L1034,2025-07-10,18500,6.0,3330.0,45
33,L1035,26-Jul-2025,KES 15000,12.0,1350.0,0
34,L1037,2025-04-22,12500,12.0,1125.0,0
35,L1038,15-Jul-2025,30000,12.0,2700.0,5
36,L1039,18/08/2025,8000,12.0,720.0,30
37,L1040,08-Feb-2025,9500,3.0,3420.0,0
38,L1041,2025-02-14,35000,3.0,12600.0,0
39,L1042,16-May-2025,41000,12.0,3690.0,0
40,L1043,2025-03-12,8000,3.0,2880.0,5
41,L1044,06-Jun-2025,12500,6.0,2250.0,30
42,L1045,2025-05-10,9500,12.0,855.0,0
43,L1046,04/08/2025,KES 30000,12.0,2700.0,5
44,L1047,2025-04-20,12500,12.0,1125.0,5
45,L1048,06/02/2025,15000,12.0,1350.0,30
46,L1049,11-Feb-2025,12500,6.0,2250.0,0
47,L1050,2025-04-18,9500,6.0,1710.0,0 days
48,L1052,2025-08-24,9500,3.0,3420.0,0
49,L1053,2025-07-13,8000,3.0,2880.0,15
50,L1054,18-May-2025,30000,6.0,5400.0,0
51,L1056,18/01/2025,30000,3.0,10800.0,5
52,L1058,2025-02-16,15000,6.0,2700.0,0
53,L1059,09-May-2025,22000,6.0,3960.0,0
54,L1060,05-Jan-2025,30000,3.0,10800.0,0
55,L1061,2025-08-02,-5000,6.0,900.0,0

In [36]:
# Rows with at least one missing value
loan_ledger_mask = loan_ledger[loan_ledger.isna().any(axis=1)]

# Rows without any missing value
clean_loan_ledger_mask = loan_ledger[~loan_ledger.isna().any(axis=1)]

# Optional: rows where every cell is null
all_null_rows = loan_ledger[loan_ledger.isna().all(axis=1)]

loan_ledger_mask, clean_loan_ledger_mask, all_null_rows

(   loan_id disbursement_date       amount  term_months  monthly_repayment  \
 3    L1004        2025-09-07          NaN          6.0             6300.0
 35   L1036        2025-05-21          NaN          3.0            14760.0
 50   L1051       23-Apr-2025          NaN         12.0             3690.0
 54   L1055        2025-04-19         8000         12.0              720.0
 56   L1057        2025-06-09          NaN          6.0             1710.0
 60     NaN               NaN          NaN          NaN                NaN
 61   TOTAL               NaN  =SUM(above)          NaN                NaN

    days_late
 3          0
 35         0
 50         0
 54       NaN
 56        15
 60       NaN
 61       NaN  ,
    loan_id disbursement_date     amount  term_months  monthly_repayment  \
 0    L1001        2025-06-16    pending          3.0            14760.0
 1    L1002        2025-01-10       8000         12.0              720.0
 2    L1003        2025-08-31      18500          3.0             6660.0
 4    L1005        27/05/2025      15000         12.0             1350.0
 5    L1006        2025-04-06      35000         12.0             3150.0
 6    L1007        20/04/2025      22000          6.0             3960.0
 7    L1008       21-Jan-2025      22000          3.0             7920.0
 8    L1009       31-Jan-2025      27000          6.0             4860.0
 9    L1010       04-Sep-2025    pending          6.0             4860.0
 10   L1011        02/06/2025      41000          6.0             7380.0
 11   L1012       16-Jan-2025      30000          6.0             5400.0
 12   L1013       16-Aug-2025      27000          6.0             4860.0
 13   L1014        2025-01-16      35000          3.0            12600.0
 14   L1015        12/02/2025      18500          6.0             3330.0
 15   L1016        30/06/2025      18500         12.0             1665.0
 16   L1017        2025-02-15      22000          3.0             7920.0
 17   L1018        2025-03-14  KES 35000          3.0            12600.0
 18   L1019       01-Sep-2025      41000          3.0            14760.0
 19   L1020        13/04/2025      9,500          6.0             1710.0
 20   L1021        2025-02-11      12500          3.0             4500.0
 21   L1022        31/08/2025      15000         12.0             1350.0
 22   L1023        02/09/2025      18500          3.0             6660.0
 23   L1024        04/05/2025    pending          6.0             4860.0
 24   L1025        2025-05-13      30000          6.0             5400.0
 25   L1026       18-Mar-2025       9500          3.0             3420.0
 26   L1027        2025-07-17      41000          3.0            14760.0
 27   L1028        2025-07-26      22000         12.0             1980.0
 28   L1029        2025-07-07       9500          6.0             1710.0
 29   L1030       25-Apr-2025      22000         12.0             1980.0
 30   L1031        2025-05-01      22000          3.0             7920.0
 31   L1032       21-Aug-2025      35000          3.0            12600.0
 32   L1033        2025-05-03      12500          6.0             2250.0
 33   L1034        2025-07-10      18500          6.0             3330.0
 34   L1035       26-Jul-2025  KES 15000         12.0             1350.0
 36   L1037        2025-04-22      12500         12.0             1125.0
 37   L1038       15-Jul-2025      30000         12.0             2700.0
 38   L1039        18/08/2025       8000         12.0              720.0
 39   L1040       08-Feb-2025       9500          3.0             3420.0
 40   L1041        2025-02-14      35000          3.0            12600.0
 41   L1042       16-May-2025      41000         12.0             3690.0
 42   L1043        2025-03-12       8000          3.0             2880.0
 43   L1044       06-Jun-2025      12500          6.0             2250.0
 44   L1045        2025-05-10       9500         12.0              855.0
 45   L1046        04/08/2025  KES 30000         12.0             2700.0
 46   L1047        2025-04-20      12500         12.0             1125.0
 47   L1048        06/02/2025      15000         12.0             1350.0
 48   L1049       11-Feb-2025      12500          6.0             2250.0
 49   L1050        2025-04-18       9500          6.0             1710.0
 51   L1052        2025-08-24       9500          3.0             3420.0
 52   L1053        2025-07-13       8000          3.0             2880.0
 53   L1054       18-May-2025      30000          6.0             5400.0
 55   L1056        18/01/2025      30000          3.0            10800.0
 57   L1058        2025-02-16      15000          6.0             2700.0
 58   L1059       09-May-2025     22000           6.0             3960.0
 59   L1060       05-Jan-2025      30000          3.0            10800.0
 62   L1061        2025-08-02      -5000          6.0              900.0

    days_late
 0         45
 1          -
 2          0
 4          0
 5          -
 6          0
 7          5
 8          0
 9          0
 10        30
 11         0
 12        45
 13         0
 14         0
 15        15
 16         0
 17        15
 18         0
 19        45
 20         -
 21         -
 22        15
 23         0
 24         0
 25         0
 26        30
 27         5
 28        30
 29        30
 30         5
 31         0
 32         5
 33        45
 34         0
 36         0
 37         5
 38        30
 39         0
 40         0
 41         0
 42         5
 43        30
 44         0
 45         5
 46         5
 47        30
 48         0
 49    0 days
 51         0
 52        15
 53         0
 55         5
 57         0
 58         0
 59         0
 62         0  ,
    loan_id disbursement_date amount  term_months  monthly_repayment days_late
 60     NaN               NaN    NaN          NaN                NaN       NaN)