# Naivas product price and discount analysis

In [560]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

<!-- Understanding the online prices on different target products
 -->

In [561]:
headers = {
    "User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
}
url = "https://www.naivas.online/naivas-bakery"

response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.content, "html.parser")
# products = soup.find_all("div", class_="product-image-container")
# print(len(products))
# position = response.text.find("Fresh Sweet Bread 400G")
# print(position)
# print(response.text[position -500:position + 1000])
# print("Fresh Sweet Bread 400G" in response.text)
products = soup.find_all("div", class_="product-image-container")
product = products[0]
print(product)
print(len(products))
products = soup.find_all("div", class_="product-image-container")
print(len(products))


product = products[0]
print(product)
link = product.find("a")
print(link)

name = link["title"]
print(name)
print(product.get_text(" ", strip=True))

parent = product.parent
print(parent.get_text(" ", strip=True))

parent2 = parent.parent
print(parent2.get_text(" ", strip=True))
print(parent2)
price_text = parent2.find(string=lambda text: text and "KES" in text)
print(price_text)

print(type(price_text))
print(price_text)

price = str(price_text)

print(price)
print(type(price))

price = price.replace("KES", "")
print(price)
print(float(price))
print(type(price))

name = "Fresh Sweet Bread 400G"
price = 54.0
product_data = {
    "name": name,
    "price": price
}
print(product_data)




data = []
for product in products:
    link = product.find("a")
    name = link["title"]
    print(name)

parent = product.parent
parent2 = parent.parent

print(parent2.get_text(" ",strip=True))

for product in products:
    link = product.find("a")
    name = link["title"]

    parent = product.parent
    parent2 = parent.parent

    price_text = parent2.find(
        string=lambda text: text and "KES" in text
    )

    print(name, price_text)

price = str(price_text)
price = price.replace("KES", "").strip()  
print(float(price))  

for product in products:
    link = product.find("a")
    name = link["title"]

    parent = product.parent
    parent2 = parent.parent

    price_text = parent2.find(
        string=lambda text: text and "KES" in text
    )

    price = str(price_text)
    price = price.replace("KES", "").strip()
    price = float(price)

    print(name, price)

    data.append({
        "name": name,
        "price": price
    })
    print(len(data))
    print(data[0])

df = pd.DataFrame(data)   
print(df)

<div class="product-image-container relative">
<div class="flex flex-row gap-2 product-img">
<a class="mx-auto" href="https://www.naivas.online/fresh-sweet-bread-400g" title="Fresh Sweet Bread 400G" wire:click="redirectToProductPage">
<div class="bg-white rounded-xl flex justify-content-center align-items-center flex-col relative product-card-img w-full">
<script data-cf-settings="95c91f8bc80a971f1577bedc-|49" src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js"></script><img alt="Fresh Sweet Bread 400G" class="h-full w-fit mx-auto rounded-xl object-contain" onerror="if (this.src != 'https://www.naivas.online/assets/placeholder/product.jpg') this.src = 'https://www.naivas.online/assets/placeholder/product.jpg';" src="https://d16zmt6hgq1jhj.cloudfront.net/product/27366/yq0eo4x7natckF2C8jjfvHb7zDi7bj6buEvxGylf.webp"/>
</div>
</a>
<div class="absolute bottom-0 left-0 m-2">
<span class="pill" id="pill-27366">Online Exclusive</span>
</div>
</div>
</div>
15
15
<div class="product-image-container relative">
<div class="flex flex-row gap-2 product-img">
<a class="mx-auto" href="https://www.naivas.online/fresh-sweet-bread-400g" title="Fresh Sweet Bread 400G" wire:click="redirectToProductPage">
<div class="bg-white rounded-xl flex justify-content-center align-items-center flex-col relative product-card-img w-full">
<script data-cf-settings="95c91f8bc80a971f1577bedc-|49" src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js"></script><img alt="Fresh Sweet Bread 400G" class="h-full w-fit mx-auto rounded-xl object-contain" onerror="if (this.src != 'https://www.naivas.online/assets/placeholder/product.jpg') this.src = 'https://www.naivas.online/assets/placeholder/product.jpg';" src="https://d16zmt6hgq1jhj.cloudfront.net/product/27366/yq0eo4x7natckF2C8jjfvHb7zDi7bj6buEvxGylf.webp"/>
</div>
</a>
<div class="absolute bottom-0 left-0 m-2">
<span class="pill" id="pill-27366">Online Exclusive</span>
</div>
</div>
</div>
<a class="mx-auto" href="https://www.naivas.online/fresh-sweet-bread-400g" title="Fresh Sweet Bread 400G" wire:click="redirectToProductPage">
<div class="bg-white rounded-xl flex justify-content-center align-items-center flex-col relative product-card-img w-full">
<script data-cf-settings="95c91f8bc80a971f1577bedc-|49" src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js"></script><img alt="Fresh Sweet Bread 400G" class="h-full w-fit mx-auto rounded-xl object-contain" onerror="if (this.src != 'https://www.naivas.online/assets/placeholder/product.jpg') this.src = 'https://www.naivas.online/assets/placeholder/product.jpg';" src="https://d16zmt6hgq1jhj.cloudfront.net/product/27366/yq0eo4x7natckF2C8jjfvHb7zDi7bj6buEvxGylf.webp"/>
</div>
</a>
Fresh Sweet Bread 400G
Online Exclusive
Online Exclusive
28% off Online Exclusive Fresh Sweet Bread 400G KES 39 KES 54 Save KES 15 ADD TO CART
<div class="border border-naivas-bg p-3 rounded-xl h-full flex justify-between flex-col hover:shadow w-full relative" wire:ignore.self="">
<div class="absolute top-0 left-0 m-2 z-20">
<span class="bg-naivas-orange/10 text-naivas-orange text-xs px-1 rounded-md">
                    28% off
                </span>
</div>
<div class="h-100 relative">
<div class="product-image-container relative">
<div class="flex flex-row gap-2 product-img">
<a class="mx-auto" href="https://www.naivas.online/fresh-sweet-bread-400g" title="Fresh Sweet Bread 400G" wire:click="redirectToProductPage">
<div class="bg-white rounded-xl flex justify-content-center align-items-center flex-col relative product-card-img w-full">
<script data-cf-settings="95c91f8bc80a971f1577bedc-|49" src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js"></script><img alt="Fresh Sweet Bread 400G" class="h-full w-fit mx-auto rounded-xl object-contain" onerror="if (this.src != 'https://www.naivas.online/assets/placeholder/product.jpg') this.src = 'https://www.naivas.online/assets/placeholder/product.jpg';" src="https://d16zmt6hgq1jhj.cloudfront.net/product/27366/yq0eo4x7natckF2C8jjfvHb7zDi7bj6buEvxGylf.webp"/>
</div>
</a>
<div class="absolute bottom-0 left-0 m-2">
<span class="pill" id="pill-27366">Online Exclusive</span>
</div>
</div>
</div>
</div>
<div class="flex flex-col grow">
<div class="text-black-50 py-2 font-medium">
<a class="!text-naivas-gray-dark text-xs lg:text-sm block" href="https://www.naivas.online/fresh-sweet-bread-400g" title="Fresh Sweet Bread 400G" wire:click="redirectToProductPage">
<span class="line-clamp-2 text-ellipsis">Fresh Sweet Bread 400G</span>
</a>
</div>
<div class="mb-4 grow">
<div class="product-price">
<p class="my-0 leading-none flex flex-col md:flex-row md:items-center"><span class="font-bold text-naivas-green mb-1 md:mb-0 pe-2">KES 39</span><span class="text-red-600 text-xs line-through font-light"> KES 54 </span></p><p class="leading-normal"><span class="text-xxs text-black-50 font-medium">Save KES 15</span></p>
</div>
</div>
<div class="w-100">
<form wire:submit="addToCart">
<input autocomplete="off" name="_token" type="hidden" value="jNFh5NmCnkF2AB4VbSToNk5Hw4Z1q80nsDdkgsXu"/> <input name="product_id" type="hidden" value="27366"/>
<input name="quantity" type="hidden" value="1"/>
<button class="w-full justify-center flex gap-2 bg-naivas-orange border hover:border hover:bg-white border-naivas-orange hover:text-naivas-orange fill-white hover:fill-naivas-orange font-gotham font-bold py-2 px-4 rounded-xl text-white">
<span class="font-normal text-xs md:text-sm flex items-center gap-2">
<span class="hidden md:inline-block">
<svg height="17" viewbox="0 0 17 17" width="17" xmlns="http://www.w3.org/2000/svg">
<path d="M16.4476 6.38016C16.2095 6.08213 15.9162 5.85101 15.5462 5.67618L15.0061 3.74037C14.7471 2.81176 14.617 2.34564 14.3102 1.94178C14.0044 1.53947 13.5904 1.23028 13.1126 1.04767C12.7065 0.892554 12.2895 0.868949 11.5724 0.865318C11.3661 0.358993 10.86 0 10.2692 0H6.73032C6.1395 0 5.63334 0.358993 5.42711 0.865318C4.70995 0.868949 4.29297 0.892554 3.88688 1.04767C3.40912 1.23002 2.99507 1.53921 2.68931 1.94178C2.38248 2.34538 2.25242 2.8115 1.99337 3.74037L1.45324 5.67618C1.08325 5.85101 0.789695 6.08213 0.551614 6.38016C0.0844746 6.96534 -0.0758391 7.68929 0.0321868 8.72814C0.126145 9.63081 0.408552 10.7348 0.79925 12.2626C1.29399 14.1968 1.56658 15.2621 2.42707 15.9186C3.28756 16.5751 4.41135 16.5751 6.45137 16.5751H10.5484C12.5884 16.5751 13.7122 16.5751 14.5727 15.9186C15.4329 15.2621 15.7055 14.1966 16.2005 12.262C16.5912 10.7342 16.8736 9.63055 16.9676 8.72788C17.0756 7.68929 16.9153 6.96508 16.4479 6.38016H16.4476ZM6.73032 1.01187H10.2692C10.4717 1.01187 10.6362 1.17295 10.6362 1.37061C10.6362 1.56826 10.4714 1.72934 10.2692 1.72934H6.73032C6.52781 1.72934 6.36325 1.56826 6.36325 1.37061C6.36325 1.17295 6.52807 1.01187 6.73032 1.01187ZM2.99215 4.0065C3.21696 3.20033 3.33003 2.79568 3.52034 2.54511C3.71011 2.29532 3.9673 2.10338 4.26378 1.99002C4.50823 1.89664 4.84186 1.88004 5.42764 1.87719C5.63414 2.38274 6.14003 2.74121 6.73032 2.74121H10.2692C10.8595 2.74121 11.3651 2.38274 11.5718 1.87719C12.1576 1.88004 12.4913 1.8969 12.7357 1.99002C13.0322 2.10338 13.2894 2.29532 13.4792 2.54485C13.6697 2.79568 13.7825 3.20007 14.0073 4.00625L14.3789 5.33846C14.3341 5.3312 14.289 5.32419 14.2425 5.31771C13.3236 5.18776 12.1592 5.18776 10.5479 5.18776H6.45084C4.83947 5.18776 3.67508 5.18776 2.75619 5.31771C2.71001 5.32419 2.66462 5.3312 2.62003 5.33846L2.99162 4.00625L2.99215 4.0065ZM15.1962 12.0172C14.7428 13.7896 14.5151 14.679 13.9357 15.1213C13.356 15.5635 12.4177 15.5635 10.5484 15.5635H6.45137C4.58202 15.5635 3.64376 15.5635 3.06408 15.1213C2.4844 14.679 2.25694 13.7893 1.8036 12.0172C1.08643 9.2132 0.72626 7.80576 1.36778 7.00269C2.0093 6.19963 3.49379 6.19963 6.45137 6.19963H10.5484C13.506 6.19963 14.9905 6.19963 15.632 7.00269C16.2735 7.80576 15.9136 9.21294 15.1962 12.0172Z" fill="currentColor"></path>
<path d="M4.96075 8.64648C4.67489 8.64648 4.44318 8.87293 4.44318 9.15229V12.6107C4.44318 12.8901 4.67489 13.1165 4.96075 13.1165C5.2466 13.1165 5.47831 12.8901 5.47831 12.6107V9.15229C5.47831 8.87293 5.2466 8.64648 4.96075 8.64648Z" fill="currentColor"></path>
<path d="M12.0387 8.64648C11.7529 8.64648 11.5212 8.87293 11.5212 9.15229V12.6107C11.5212 12.8901 11.7529 13.1165 12.0387 13.1165C12.3246 13.1165 12.5563 12.8901 12.5563 12.6107V9.15229C12.5563 8.87293 12.3246 8.64648 12.0387 8.64648Z" fill="currentColor"></path>
<path d="M8.49987 8.64648C8.21401 8.64648 7.9823 8.87293 7.9823 9.15229V12.6107C7.9823 12.8901 8.21401 13.1165 8.49987 13.1165C8.78573 13.1165 9.01744 12.8901 9.01744 12.6107V9.15229C9.01744 8.87293 8.78573 8.64648 8.49987 8.64648Z" fill="currentColor"></path>
</svg>
</span>
<span>
                            ADD TO CART
                        </span>
</span>
</button>
</form>
</div>
</div>
</div>
KES 39
<class 'bs4.element.NavigableString'>
KES 39
KES 39
<class 'str'>
 39
39.0
<class 'str'>
{'name': 'Fresh Sweet Bread 400G', 'price': 54.0}
Fresh Sweet Bread 400G
Fresh Vanilla Muffins 6Pc
Fresh Plain Buns 400G
Fresh Ginger Cookies 200G
Fresh Chocolate Cookies 200G
Fresh Blueberry Muffin 6S
Fresh Coconut Muffin 6-S
Fresh Queen Cake 6S
Fresh Chocolate Chip Muffin 6S
Fresh White Bread 600G
Fresh Wholemeal Bread 800G
Fresh Wholemeal Bread 600G
Fresh White Bread 800Gm
Fresh White Bread 400G
Fresh Choco Doughnuts 120G
Fresh Choco Doughnuts 120G KES 65 ADD TO CART
Fresh Sweet Bread 400G KES 39
Fresh Vanilla Muffins 6Pc KES 179
Fresh Plain Buns 400G KES 85
Fresh Ginger Cookies 200G KES 90
Fresh Chocolate Cookies 200G KES 90
Fresh Blueberry Muffin 6S KES 179
Fresh Coconut Muffin 6-S KES 179
Fresh Queen Cake 6S KES 109
Fresh Chocolate Chip Muffin 6S KES 179
Fresh White Bread 600G KES 89
Fresh Wholemeal Bread 800G KES 118
Fresh Wholemeal Bread 600G KES 90
Fresh White Bread 800Gm KES 117
Fresh White Bread 400G KES 57
Fresh Choco Doughnuts 120G KES 65
65.0
Fresh Sweet Bread 400G 39.0
1
{'name': 'Fresh Sweet Bread 400G', 'price': 39.0}
Fresh Vanilla Muffins 6Pc 179.0
2
{'name': 'Fresh Sweet Bread 400G', 'price': 39.0}
Fresh Plain Buns 400G 85.0
3
{'name': 'Fresh Sweet Bread 400G', 'price': 39.0}
Fresh Ginger Cookies 200G 90.0
4
{'name': 'Fresh Sweet Bread 400G', 'price': 39.0}
Fresh Chocolate Cookies 200G 90.0
5
{'name': 'Fresh Sweet Bread 400G', 'price': 39.0}
Fresh Blueberry Muffin 6S 179.0
6
{'name': 'Fresh Sweet Bread 400G', 'price': 39.0}
Fresh Coconut Muffin 6-S 179.0
7
{'name': 'Fresh Sweet Bread 400G', 'price': 39.0}
Fresh Queen Cake 6S 109.0
8
{'name': 'Fresh Sweet Bread 400G', 'price': 39.0}
Fresh Chocolate Chip Muffin 6S 179.0
9
{'name': 'Fresh Sweet Bread 400G', 'price': 39.0}
Fresh White Bread 600G 89.0
10
{'name': 'Fresh Sweet Bread 400G', 'price': 39.0}
Fresh Wholemeal Bread 800G 118.0
11
{'name': 'Fresh Sweet Bread 400G', 'price': 39.0}
Fresh Wholemeal Bread 600G 90.0
12
{'name': 'Fresh Sweet Bread 400G', 'price': 39.0}
Fresh White Bread 800Gm 117.0
13
{'name': 'Fresh Sweet Bread 400G', 'price': 39.0}
Fresh White Bread 400G 57.0
14
{'name': 'Fresh Sweet Bread 400G', 'price': 39.0}
Fresh Choco Doughnuts 120G 65.0
15
{'name': 'Fresh Sweet Bread 400G', 'price': 39.0}
                              name  price
0           Fresh Sweet Bread 400G   39.0
1        Fresh Vanilla Muffins 6Pc  179.0
2            Fresh Plain Buns 400G   85.0
3        Fresh Ginger Cookies 200G   90.0
4     Fresh Chocolate Cookies 200G   90.0
5        Fresh Blueberry Muffin 6S  179.0
6         Fresh Coconut Muffin 6-S  179.0
7              Fresh Queen Cake 6S  109.0
8   Fresh Chocolate Chip Muffin 6S  179.0
9           Fresh White Bread 600G   89.0
10      Fresh Wholemeal Bread 800G  118.0
11      Fresh Wholemeal Bread 600G   90.0
12         Fresh White Bread 800Gm  117.0
13          Fresh White Bread 400G   57.0
14      Fresh Choco Doughnuts 120G   65.0

In [562]:
# understanding the data

print(df.shape)


print(df.info())

(15, 2)
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    15 non-null     str
 1   price   15 non-null     float64
dtypes: float64(1), str(1)
memory usage: 372.0 bytes
None

# Data has 15 non-null rows
# 2 columns
# 15 numbers and no missing columns

In [563]:
#  checking to see if there empty data cells,duplicates or unusual values

# cleaning the data

print(df.isna().sum())

name     0
price    0
dtype: int64

In [564]:
# checking duplicates

print(df.duplicated().sum())

0

# name - text
# price = numeric
# 15 nun null rows
# 2 columns
# 0 duplicates
# 0 missing values

In [565]:
print(df["name"].duplicated().sum())

0

In [566]:
# claen view of the crapped data set

print(df.to_string(index=False))

                          name  price
        Fresh Sweet Bread 400G   39.0
     Fresh Vanilla Muffins 6Pc  179.0
         Fresh Plain Buns 400G   85.0
     Fresh Ginger Cookies 200G   90.0
  Fresh Chocolate Cookies 200G   90.0
     Fresh Blueberry Muffin 6S  179.0
      Fresh Coconut Muffin 6-S  179.0
           Fresh Queen Cake 6S  109.0
Fresh Chocolate Chip Muffin 6S  179.0
        Fresh White Bread 600G   89.0
    Fresh Wholemeal Bread 800G  118.0
    Fresh Wholemeal Bread 600G   90.0
       Fresh White Bread 800Gm  117.0
        Fresh White Bread 400G   57.0
    Fresh Choco Doughnuts 120G   65.0

In [567]:
# understanding the data

df["price"].describe()

count     15.000000
mean     111.000000
std       47.271254
min       39.000000
25%       87.000000
50%       90.000000
75%      148.500000
max      179.000000
Name: price, dtype: float64

In [568]:
# sorting values to know actually how much every product cost
# to know which products produced those numbers

df.sort_values("price")


# incase changing the indexes df.sort_values("price").reset_index(drop=True)

                              name  price
0           Fresh Sweet Bread 400G   39.0
13          Fresh White Bread 400G   57.0
14      Fresh Choco Doughnuts 120G   65.0
2            Fresh Plain Buns 400G   85.0
9           Fresh White Bread 600G   89.0
11      Fresh Wholemeal Bread 600G   90.0
3        Fresh Ginger Cookies 200G   90.0
4     Fresh Chocolate Cookies 200G   90.0
7              Fresh Queen Cake 6S  109.0
12         Fresh White Bread 800Gm  117.0
10      Fresh Wholemeal Bread 800G  118.0
1        Fresh Vanilla Muffins 6Pc  179.0
6         Fresh Coconut Muffin 6-S  179.0
5        Fresh Blueberry Muffin 6S  179.0
8   Fresh Chocolate Chip Muffin 6S  179.0

In [569]:
#  re arraging the the data

df.sort_values("price").reset_index(drop=True)

                              name  price
0           Fresh Sweet Bread 400G   39.0
1           Fresh White Bread 400G   57.0
2       Fresh Choco Doughnuts 120G   65.0
3            Fresh Plain Buns 400G   85.0
4           Fresh White Bread 600G   89.0
5       Fresh Wholemeal Bread 600G   90.0
6        Fresh Ginger Cookies 200G   90.0
7     Fresh Chocolate Cookies 200G   90.0
8              Fresh Queen Cake 6S  109.0
9          Fresh White Bread 800Gm  117.0
10      Fresh Wholemeal Bread 800G  118.0
11       Fresh Vanilla Muffins 6Pc  179.0
12        Fresh Coconut Muffin 6-S  179.0
13       Fresh Blueberry Muffin 6S  179.0
14  Fresh Chocolate Chip Muffin 6S  179.0

In [570]:
# getting the mean 

print(df["price"].mean())

111.0

In [571]:
# understanding what products cost more than the averange

df[df["price"] > df["price"].mean()]

                              name  price
1        Fresh Vanilla Muffins 6Pc  179.0
5        Fresh Blueberry Muffin 6S  179.0
6         Fresh Coconut Muffin 6-S  179.0
8   Fresh Chocolate Chip Muffin 6S  179.0
10      Fresh Wholemeal Bread 800G  118.0
12         Fresh White Bread 800Gm  117.0

In [572]:
df["name"]

0             Fresh Sweet Bread 400G
1          Fresh Vanilla Muffins 6Pc
2              Fresh Plain Buns 400G
3          Fresh Ginger Cookies 200G
4       Fresh Chocolate Cookies 200G
5          Fresh Blueberry Muffin 6S
6           Fresh Coconut Muffin 6-S
7                Fresh Queen Cake 6S
8     Fresh Chocolate Chip Muffin 6S
9             Fresh White Bread 600G
10        Fresh Wholemeal Bread 800G
11        Fresh Wholemeal Bread 600G
12           Fresh White Bread 800Gm
13            Fresh White Bread 400G
14        Fresh Choco Doughnuts 120G
Name: name, dtype: str

In [573]:
split_name = df["name"].str.split()
split_name[0]

['Fresh', 'Sweet', 'Bread', '400G']

In [574]:
print(split_name[0][-1])
print(split_name[1][-1])
print(split_name[2][-1])
print(split_name[3][-1])
print(split_name[4][-2])
print(split_name[5][-2])
print(split_name[6][-2])
print(split_name[7][-2])
print(split_name[8][-1])
print(split_name[9][-1])
print(split_name[10][-1])
print(split_name[11][-1])
print(split_name[12][-1])
print(split_name[13][-1])
print(split_name[14][-1])

400G
6Pc
400G
200G
Cookies
Muffin
Muffin
Cake
6S
600G
800G
600G
800Gm
400G
120G

In [575]:
print(split_name[5])
print(split_name[6])
print(split_name[7])

['Fresh', 'Blueberry', 'Muffin', '6S']
['Fresh', 'Coconut', 'Muffin', '6-S']
['Fresh', 'Queen', 'Cake', '6S']

In [576]:
for i in range(len(split_name)):
    print(i, split_name[i][-1])

0 400G
1 6Pc
2 400G
3 200G
4 200G
5 6S
6 6-S
7 6S
8 6S
9 600G
10 800G
11 600G
12 800Gm
13 400G
14 120G

In [577]:
split_name[7][-1]

'6S'

In [578]:
for item in split_name:
    print(item[-1])

400G
6Pc
400G
200G
200G
6S
6-S
6S
6S
600G
800G
600G
800Gm
400G
120G

In [579]:
sizes = []
for item in split_name:
    sizes.append(item[-1])
print(sizes)

['400G', '6Pc', '400G', '200G', '200G', '6S', '6-S', '6S', '6S', '600G', '800G', '600G', '800Gm', '400G', '120G']

In [580]:
df["size or quantity"] = sizes
print(df)

                              name  price size or quantity
0           Fresh Sweet Bread 400G   39.0             400G
1        Fresh Vanilla Muffins 6Pc  179.0              6Pc
2            Fresh Plain Buns 400G   85.0             400G
3        Fresh Ginger Cookies 200G   90.0             200G
4     Fresh Chocolate Cookies 200G   90.0             200G
5        Fresh Blueberry Muffin 6S  179.0               6S
6         Fresh Coconut Muffin 6-S  179.0              6-S
7              Fresh Queen Cake 6S  109.0               6S
8   Fresh Chocolate Chip Muffin 6S  179.0               6S
9           Fresh White Bread 600G   89.0             600G
10      Fresh Wholemeal Bread 800G  118.0             800G
11      Fresh Wholemeal Bread 600G   90.0             600G
12         Fresh White Bread 800Gm  117.0            800Gm
13          Fresh White Bread 400G   57.0             400G
14      Fresh Choco Doughnuts 120G   65.0             120G

In [581]:
print("400G".endswith("G"))
print("6S".endswith("G"))

True
False

In [582]:

for size in sizes:
    print(size, size.endswith(("G","Gm")))

400G True
6Pc False
400G True
200G True
200G True
6S False
6-S False
6S False
6S False
600G True
800G True
600G True
800Gm True
400G True
120G True

In [583]:
print("400G".endswith(("G", "Gm")))
print("800Gm".endswith(("G", "Gm")))
print("6S".endswith(("G","Gm")))

True
True
False

In [584]:
weights = []
for size in sizes:
    if size.endswith(("G","Gm")):
        weights.append(size)
    else:
        weights.append(None)
print(weights)

['400G', None, '400G', '200G', '200G', None, None, None, None, '600G', '800G', '600G', '800Gm', '400G', '120G']

In [585]:
print(type(weights[4]))

df["quantity"] = weights
df

<class 'str'>

                              name  price size or quantity quantity
0           Fresh Sweet Bread 400G   39.0             400G     400G
1        Fresh Vanilla Muffins 6Pc  179.0              6Pc      NaN
2            Fresh Plain Buns 400G   85.0             400G     400G
3        Fresh Ginger Cookies 200G   90.0             200G     200G
4     Fresh Chocolate Cookies 200G   90.0             200G     200G
5        Fresh Blueberry Muffin 6S  179.0               6S      NaN
6         Fresh Coconut Muffin 6-S  179.0              6-S      NaN
7              Fresh Queen Cake 6S  109.0               6S      NaN
8   Fresh Chocolate Chip Muffin 6S  179.0               6S      NaN
9           Fresh White Bread 600G   89.0             600G     600G
10      Fresh Wholemeal Bread 800G  118.0             800G     800G
11      Fresh Wholemeal Bread 600G   90.0             600G     600G
12         Fresh White Bread 800Gm  117.0            800Gm    800Gm
13          Fresh White Bread 400G   57.0             400G     400G
14      Fresh Choco Doughnuts 120G   65.0             120G     120G

In [586]:
df.columns

Index(['name', 'price', 'size or quantity', 'quantity'], dtype='str')

In [587]:
df.rename(columns={"quantity":"weight"})

                              name  price size or quantity weight
0           Fresh Sweet Bread 400G   39.0             400G   400G
1        Fresh Vanilla Muffins 6Pc  179.0              6Pc    NaN
2            Fresh Plain Buns 400G   85.0             400G   400G
3        Fresh Ginger Cookies 200G   90.0             200G   200G
4     Fresh Chocolate Cookies 200G   90.0             200G   200G
5        Fresh Blueberry Muffin 6S  179.0               6S    NaN
6         Fresh Coconut Muffin 6-S  179.0              6-S    NaN
7              Fresh Queen Cake 6S  109.0               6S    NaN
8   Fresh Chocolate Chip Muffin 6S  179.0               6S    NaN
9           Fresh White Bread 600G   89.0             600G   600G
10      Fresh Wholemeal Bread 800G  118.0             800G   800G
11      Fresh Wholemeal Bread 600G   90.0             600G   600G
12         Fresh White Bread 800Gm  117.0            800Gm  800Gm
13          Fresh White Bread 400G   57.0             400G   400G
14      Fresh Choco Doughnuts 120G   65.0             120G   120G

In [588]:
df.columns

Index(['name', 'price', 'size or quantity', 'quantity'], dtype='str')

In [589]:
df = df.rename(columns={"quantity": "weight"})
df

                              name  price size or quantity weight
0           Fresh Sweet Bread 400G   39.0             400G   400G
1        Fresh Vanilla Muffins 6Pc  179.0              6Pc    NaN
2            Fresh Plain Buns 400G   85.0             400G   400G
3        Fresh Ginger Cookies 200G   90.0             200G   200G
4     Fresh Chocolate Cookies 200G   90.0             200G   200G
5        Fresh Blueberry Muffin 6S  179.0               6S    NaN
6         Fresh Coconut Muffin 6-S  179.0              6-S    NaN
7              Fresh Queen Cake 6S  109.0               6S    NaN
8   Fresh Chocolate Chip Muffin 6S  179.0               6S    NaN
9           Fresh White Bread 600G   89.0             600G   600G
10      Fresh Wholemeal Bread 800G  118.0             800G   800G
11      Fresh Wholemeal Bread 600G   90.0             600G   600G
12         Fresh White Bread 800Gm  117.0            800Gm  800Gm
13          Fresh White Bread 400G   57.0             400G   400G
14      Fresh Choco Doughnuts 120G   65.0             120G   120G

In [590]:
print(df.columns)

Index(['name', 'price', 'size or quantity', 'weight'], dtype='str')

In [591]:
df["weight"][0]

'400G'

In [592]:
int(df["weight"][0].replace("G",""))

400

In [593]:
df["weight"].tolist()

['400G',
 nan,
 '400G',
 '200G',
 '200G',
 nan,
 nan,
 nan,
 nan,
 '600G',
 '800G',
 '600G',
 '800Gm',
 '400G',
 '120G']

In [594]:
pd.isna(df["weight"][1])

True

In [595]:


for weight in df["weight"]:
    print(weight)

400G
nan
400G
200G
200G
nan
nan
nan
nan
600G
800G
600G
800Gm
400G
120G

In [596]:
for weight in df["weight"]:
    if pd.isna(weight):
        print("missing")
    else:
        print(weight)

400G
missing
400G
200G
200G
missing
missing
missing
missing
600G
800G
600G
800Gm
400G
120G

In [597]:
numeric_weights = []
for weight in df["weight"]:
    if pd.isna(weight):
        numeric_weights.append(None)
    else:
        numeric_weights.append(int(weight.replace("G","").replace("m","")))
        # (int(weight.replace("G", "").replace("m", "")))

In [598]:
print(numeric_weights)

[400, None, 400, 200, 200, None, None, None, None, 600, 800, 600, 800, 400, 120]

In [600]:
df["weight"] = numeric_weights
df

                              name  price size or quantity  weight
0           Fresh Sweet Bread 400G   39.0             400G   400.0
1        Fresh Vanilla Muffins 6Pc  179.0              6Pc     NaN
2            Fresh Plain Buns 400G   85.0             400G   400.0
3        Fresh Ginger Cookies 200G   90.0             200G   200.0
4     Fresh Chocolate Cookies 200G   90.0             200G   200.0
5        Fresh Blueberry Muffin 6S  179.0               6S     NaN
6         Fresh Coconut Muffin 6-S  179.0              6-S     NaN
7              Fresh Queen Cake 6S  109.0               6S     NaN
8   Fresh Chocolate Chip Muffin 6S  179.0               6S     NaN
9           Fresh White Bread 600G   89.0             600G   600.0
10      Fresh Wholemeal Bread 800G  118.0             800G   800.0
11      Fresh Wholemeal Bread 600G   90.0             600G   600.0
12         Fresh White Bread 800Gm  117.0            800Gm   800.0
13          Fresh White Bread 400G   57.0             400G   400.0
14      Fresh Choco Doughnuts 120G   65.0             120G   120.0

In [602]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              15 non-null     str
 1   price             15 non-null     float64
 2   size or quantity  15 non-null     str
 3   weight            10 non-null     float64
dtypes: float64(2), str(2)
memory usage: 612.0 bytes